#Requires -Version 7.0

# =============================== #
#    Check System Requirements    #
# ------------------------------- #
# 1. Checking os                  #
# 2. Checking Shell               #
# 3. Checking Dependencies        #
# =============================== #

[CmdletBinding()]
param(
  # 確認プロンプトを出さずに oh-my-posh をインストールする
  [switch]$InstallDeps
)

$ErrorActionPreference = 'Stop'

# 1. Checking os ---------------- #
if (-not $IsWindows) {
  Write-Host '❌️ This setup script is intended for Windows systems only.' -ForegroundColor Red
  exit 1
}

# 2. Checking Shell ------------- #
if ($PSVersionTable.PSEdition -ne 'Core') {
  Write-Host '⚠️ PowerShell 7 (pwsh) で実行してください。' -ForegroundColor Yellow
  exit 1
}

# 3. Checking Dependencies ------ #
if (-not (Get-Command oh-my-posh -ErrorAction SilentlyContinue)) {
  Write-Host '⚠️ oh-my-posh がインストールされていません。' -ForegroundColor Yellow

  if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    Write-Host '   winget も見つかりません。先に oh-my-posh を手動でインストールしてください。' -ForegroundColor Yellow
    exit 1
  }

  $answer = if ($InstallDeps) { 'y' } else { Read-Host 'winget でインストールしますか? [y/N]' }
  if ($answer -notmatch '^[Yy]') {
    Write-Host '   winget install JanDeDobbeleer.OhMyPosh -s winget を実行してから再度お試しください。'
    exit 1
  }

  winget install JanDeDobbeleer.OhMyPosh -s winget
  if ($LASTEXITCODE -ne 0) {
    Write-Host '❌️ oh-my-posh のインストールに失敗しました。' -ForegroundColor Red
    exit 1
  }

  # インストール直後は PATH がこのセッションに反映されていないので補う
  $poshBin = Join-Path $env:LOCALAPPDATA 'Programs\oh-my-posh\bin'
  if (Test-Path -LiteralPath $poshBin) { $env:PATH = "$poshBin;$env:PATH" }
}

# =============================== #
#          Symlink Setup          #
# ------------------------------- #
# 1. PowerShell profile           #
# =============================== #

# dotfiles ディレクトリの絶対パス
$DotfilesDir = Split-Path -Parent $PSScriptRoot
$SourceProfile = Join-Path $DotfilesDir 'windows/powershell/Microsoft.PowerShell_profile.ps1'

if (-not (Test-Path -LiteralPath $SourceProfile)) {
  Write-Host "❌️ プロファイルが見つかりません: $SourceProfile" -ForegroundColor Red
  exit 1
}

# $PROFILE の置き場所がなければ作る
$ProfileDir = Split-Path -Parent $PROFILE
if (-not (Test-Path -LiteralPath $ProfileDir)) {
  New-Item -ItemType Directory -Path $ProfileDir -Force | Out-Null
}

# 既存プロファイルの退避 (中身のある実ファイルのみ)
$existing = Get-Item -LiteralPath $PROFILE -Force -ErrorAction SilentlyContinue
if ($existing -and -not $existing.LinkType -and $existing.Length -gt 0) {
  $backup = "$PROFILE.$(Get-Date -Format 'yyyyMMddHHmmss').bak"
  Move-Item -LiteralPath $PROFILE -Destination $backup
  Write-Host "🗃️ 既存のプロファイルを退避しました: $backup"
} elseif ($existing) {
  Remove-Item -LiteralPath $PROFILE -Force
}

# シンボリックリンクを試し、権限がなければ dot-source するスタブを書き出す
# (Windows のシンボリックリンク作成には開発者モードか管理者権限が必要)
try {
  New-Item -ItemType SymbolicLink -Path $PROFILE -Target $SourceProfile -ErrorAction Stop | Out-Null
  Write-Host "🔗 $PROFILE -> $SourceProfile"
} catch {
  $stub = @"
# Generated by dotfiles/windows/setup.ps1 - do not edit.
`$env:DOTFILES_DIR = '$DotfilesDir'
. (Join-Path `$env:DOTFILES_DIR 'windows/powershell/Microsoft.PowerShell_profile.ps1')
"@
  Set-Content -LiteralPath $PROFILE -Value $stub -Encoding utf8NoBOM
  Write-Host '📄 シンボリックリンクを作成できなかったため、dot-source するスタブを書き出しました。'
  Write-Host '   (開発者モードを有効にすると次回からリンクになります)'
}

Write-Host ''
Write-Host '💡 プロンプトの記号を正しく表示するには、ターミナルのフォントに Nerd Font を設定してください。'
Write-Host '✅ Setup completed successfully!' -ForegroundColor Green
